version: '3.1'

services:

  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./blog/.env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./blog/.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080